// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyShop.Core.Context;

#nullable disable

namespace ToyShop.Core.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyShop.Core.Models.Administration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Administrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Dick@gmail.com",
                            FirstName = "Richard",
                            LastName = "Spenser",
                            Login = "Admin",
                            MiddleName = "Swen",
                            Password = "qwerty"
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfOpen")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            DateOfOpen = new DateOnly(2000, 5, 12),
                            Name = "lego",
                            Site = "lego.com"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            DateOfOpen = new DateOnly(2000, 5, 12),
                            Name = "Hasbro",
                            Site = "Hasbro.com"
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_cat")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name_cat")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name_cat = "Конструкторы"
                        },
                        new
                        {
                            Id = 2,
                            Name_cat = "Настольные игры"
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfRegistration")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1996, 5, 12),
                            DateOfRegistration = new DateOnly(1, 1, 1),
                            Email = "vinir@mail.ru",
                            FirstName = "Анна",
                            LastName = "Винирова",
                            MiddleName = "Сергеевна",
                            Number = "89832343234"
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Barcode")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name_prod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity_sklad")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 0,
                            Article = "Monopslia",
                            Barcode = 190,
                            BrandId = 2,
                            CategoryId = 2,
                            Name_prod = "Монополия",
                            Price = 2000m,
                            Quantity_sklad = 40,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 6,
                            Article = "Uno",
                            Barcode = 200,
                            BrandId = 2,
                            CategoryId = 2,
                            Name_prod = "UNO",
                            Price = 1300m,
                            Quantity_sklad = 100,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 3,
                            Article = "Duplo",
                            Barcode = 13,
                            BrandId = 1,
                            CategoryId = 1,
                            Name_prod = "Lego Duplo",
                            Price = 3500m,
                            Quantity_sklad = 200,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 14,
                            Article = "Techno",
                            Barcode = 16,
                            BrandId = 1,
                            CategoryId = 1,
                            Name_prod = "Lego Technic",
                            Price = 6000m,
                            Quantity_sklad = 150,
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_sale")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date_sale = new DateTime(2026, 10, 12, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 2,
                            Status = 2,
                            TotalAmount = 4000m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            Date_sale = new DateTime(2026, 10, 12, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 3,
                            Status = 3,
                            TotalAmount = 3900m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            Date_sale = new DateTime(2026, 10, 12, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 1,
                            Status = 4,
                            TotalAmount = 3500m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            Date_sale = new DateTime(2026, 10, 12, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 10,
                            Status = 1,
                            TotalAmount = 60000m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country_sup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_sup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country_sup = "Россия",
                            Name_sup = "ООО \"Марка\"",
                            Number = "89803934959"
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Tom@gmail.com",
                            FirstName = "Tom",
                            LastName = "Spenser",
                            Login = "LilTom",
                            MiddleName = "Lil",
                            Password = "qwerty"
                        });
                });

            modelBuilder.Entity("ToyShop.Core.Models.Product", b =>
                {
                    b.HasOne("ToyShop.Core.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyShop.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyShop.Core.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ToyShop.Core.Models.Sale", b =>
                {
                    b.HasOne("ToyShop.Core.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyShop.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyShop.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
